spring:
  datasource:
    url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
camunda:
  bpm:
    admin-user:
      password: demo
      id: demo
      last-name: demo
      first-name: demo
      email: demo